name: UtilityPlugin
version: '${project.version}'
main: com.utility.plugin.UtilityPlugin
api-version: '1.21'
authors: [UtilityPlugin Team]
description: A comprehensive Minecraft utility plugin with modern OOP principles
website: https://github.com/utility/utility-plugin
license: MIT

commands:
  gamemode:
    description: Change gamemode for yourself or another player
    usage: /<command> [gamemode] [player]
    aliases: [gm]
    permission: utility.gamemode
  god:
    description: Toggle god mode for yourself or another player
    usage: /<command> [player]
    permission: utility.god
  openinv:
    description: Open another player's inventory
    usage: /<command> <player>
    aliases: [invsee, openinventory]
    permission: utility.openinv
  enderchest:
    description: Open another player's ender chest
    usage: /<command> <player>
    aliases: [echest, enderchest]
    permission: utility.enderchest
  fix:
    description: Repair all items for yourself or another player
    usage: /<command> [player]
    aliases: [repair]
    permission: utility.fix
  tpa:
    description: Send a teleport request to another player
    usage: /<command> <player>
    permission: utility.tpa
  tpaccept:
    description: Accept a teleport request
    usage: /<command>
    aliases: [tpaccept]
    permission: utility.tpa
  tpadeny:
    description: Deny a teleport request
    usage: /<command>
    aliases: [tpadeny]
    permission: utility.tpa
  trash:
    description: Open a trash GUI to delete items
    usage: /<command>
    permission: utility.trash

permissions:
  utility.gamemode:
    description: Allows changing gamemode
    default: op
  utility.god:
    description: Allows toggling god mode
    default: op
  utility.openinv:
    description: Allows opening other players' inventories
    default: op
  utility.enderchest:
    description: Allows opening other players' ender chests
    default: op
  utility.fix:
    description: Allows repairing items
    default: op
  utility.tpa:
    description: Allows using teleport request commands
    default: op
  utility.trash:
    description: Allows using the trash GUI
    default: op
  utility.*:
    description: Gives access to all utility commands
    default: op
    children:
      utility.gamemode: true
      utility.god: true
      utility.openinv: true
      utility.enderchest: true
      utility.fix: true
      utility.tpa: true
      utility.trash: true 